apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-deployment
#  namespace: myns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-container
        image: notes-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DB_NAME
          value: notesdb
        - name: DB_USER
          value: root
        - name: DB_PASSWORD
          value: root
        - name: DB_HOST
          value: mysql-service
        - name: DB_PORT
          value: "3306"
